name: tests
on:
  pull_request:
  push:
    branches:
      - master

jobs:
  tests:
    name: test on ubuntu-latest
    runs-on: ubuntu-latest
    defaults:
      run:
        shell: bash

    steps:
      - name: Cache
        uses: actions/cache@v2
        with:
          path: ~/.dove
          key: ${{ matrix.cfg.os }}-dove
      - name: Fetch latest move-tools dove binary
        uses: pontem-network/get-dove@main
        with:
          version: 1.2.0
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Test
        run: dove test
