name: tests
on:
  pull_request:
  push:
    branches:
      - master

jobs:
  tests:
    name: test on ubuntu-latest
    runs-on: ubuntu-latest
    defaults:
      run:
        shell: bash

    strategy:
      fail-fast: false

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Fetch latest move-tools dove binary
        uses: dsaltares/fetch-gh-release-asset@master
        with:
          repo: "pontem-network/move-tools"
          version: "latest"
          file: dove-1.1.4-linux-x86_64

      - name: Rename dove
        run: mv dove-1.1.4-linux-x86_64 dove

      - name: set executable permissions
        run: sudo chown runner ./dove && chmod +x ./dove

      - name: Test
        run: ./dove test
